schema_version = "1.0.0"

id = "T4A_quick_baker"  # root folder name with underscores
name = "T4A Quick Baker"
version = "3.0.0"
tagline = "PBR Texture Baker"
maintainer = "Tech4ART (Karan @b3dhub)"
type = "add-on"
tags = ["Bake"]
website = "https://b3dhub.github.io/quick-baker-docs"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2022-2025 Tech4Art"]

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#     "./wheels/qbpy-1.0.0-py3-none-any.whl",
# ]

[permissions]
files = "Add-on saves textures to disk"
